name: PR Alert for MS Teams
on:
  pull_request_review:
    types:
      - submitted  

jobs:
  pr-alert:
    runs-on: ubuntu-latest   
    if: github.event.pull_request.base.ref == 'main'
    steps:
      - name: Hello world
        run: echo Hello world from ${{github.event.pull_request.base.ref}}!
      - name: GitHub Script
        uses: actions/github-script@v2.1.0
        with:
          # The script to run
          script: |
            console.log("test comment");
