name: PR Alert for MS Teams
on:
  pull_request_review:
    types:
      - submitted
    branches:
      - 'main'

jobs:
  pr-alert:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Script
        uses: actions/github-script@v2.1.0
        with:
          # The script to run
          script: |
            console.log("test comment");
          
         
          
