name: PR Alert for MS Teams
on:
  pull_request_target:
    types:
      - opened

jobs:
  pr-alert:
    runs-on: ubuntu-latest
    steps:
      - name: print payload
        run: |
          echo ${{ github.event.pull_request }}
