name: PR Alert for MS Teams
on:
  pull_request_target:
    types:
      - submitted
    branches:
      - 'main'

jobs:
  pr-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Execute JavaScript inline 
        uses: satackey/action-js-inline@v0.0.2
        with:          
          script:
           console.log(JSON.stringify(${{github.event.pull_request}}))
          
