name: PR Alert for MS Teams
on:
  pull_request_review:
    types:
      - submitted  

jobs:
  pr-alert:
    runs-on: ubuntu-latest    
    steps:
      - name: Hello world
        run: echo Hello world from $GITHUB_BASE_REF!
      - name: GitHub Script
        uses: actions/github-script@v2.1.0
        with:
          # The script to run
          script: |
            console.log("test comment");
